### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by Alex293** [Wouter125/BottomSheet#18]
Hi, I'm playing around with the new version and it's quite nice ! 

I'm currently having 2 issues : 

• first I think the Spacer() at the top of SheetPlus.body is useless and It actually cause an issue when using full height and trying to touch the NavigationBar with the sheet. Removing it fixed the issue. If it's intended to be there maybe this should be configurable ?

• second I couldn't find the correct way to add a NavigationView as the body of the sheet. If I add a NavigationView it break some constraints. I figured I could set ideal frame to the NavigationView and it shows but then the scrolling behaviour is no longer working inside the scrolling content. Depending if I add a scrollview to the content inside the NavigationView, I either have the navbar working or the scroll.

I'm not sure how to fix the second issue, iterating child views to find a scrollview and adding your scroll behaviour and if no scrollview if found adding one like you do might work but it might be hard to be sure to stop on the right scrollview. I believe the Apple version use something like that but don't look too deep in the childviews.

I'll make a fork to display the issue.

**Comment by Wouter125** [comment]
Thank you for the input. Let me see what I can do. 

1. At a certain point I did add the spacer(), but might be that it is now redundant. Will see if it is still needed and otherwise remove it in the next version. I think it was added so the in animation of the sheet when coming through a navigation view does not break. But I think we can workaround that with some other alignments. If you remove it and set the offset to the following `.offset(y: UIScreen.main.bounds.height - translation)` it should also work. Not completely sure if that causes any other issues.

2. I did not try using a navigationview inside the sheet yet. But I think you are experiencing the same issues as that I had with Lists. You do need to set an explicit frame size, because if you currently add it, it will go into the UIScrollView, but the navigationview has a scrollview of it's own. Laying out two scrollviews breaks. This issue also arises with lists since they provide a scrollview of themselves as well. A proper solution would be to use the scrollview of either one of the views, mine or the one from whatever other view it is coming from. But there are too many issues. You can see my introspection attempt in this [branch](https://github.com/Wouter125/BottomSheet/pull/15). But it has too many edge cases. I got it to work for 1 list, but as soon as you stack other views under or over it, swiftUI triggers some relayout that breaks everything unfortunately.

**Comment by Wouter125** [comment]
Additional spacer has been removed in the latest alpha release. Please check it out! 

The second issue is a large one I guess. Unless you have an idea on how to resolve that. I added it to the backlog but already spent quiet some time on it, and not sure how to solve it.

**Comment by Alex293** [comment]
Great I'll check it out. For the second issue I don't have a complete solution in mind I'll try to poke something but I don't need it right now so I'm might spend time on a solution later.
